### PR TITLE
Update npm packages

### PR DESCRIPTION
**Pull request by jrson83**
### Reference Issues/PRs

None

### What does this implement/fix?

- Updated all npm packages to the newest version
- Fixed todoList undefined error related to 067790eba98d0b9f0df3d48e9eb6310fb4d5a037
- Added notice related LazyLoad error on Chrome & Firefox (localhost)

### CODE REVIEW

**Comment by yandeu** [comment]
node-fetch@3 is esm only. Not sure if it will work. Lets wait the CI test.

Edit:
Build did work, but I will check it manually before merging.

**Comment by yandeu** [comment]
If you downgrade node-fetch to v2 I will merge it immediately.

**Comment by jrson83** [comment]
> If you downgrade node-fetch to v2 I will merge it immediately.

Ok, I will do.

**Comment by jrson83** [comment]
Sorry I should have checked before. Server should start now.

**Pull request merged**
